name: bonita-sca
services:
  greenmail:
    container_name: greenmail
    image: greenmail/standalone:2.1.0
    hostname: greenmail
    ports:
      - 2525:3025
      - 3110:3110
      - 3143:3143
      - 3465:3465
      - 3993:3993
      - 3995:3995
    restart: always
    environment:
      - GREENMAIL_OPTS=-Dgreenmail.setup.test.all -Dgreenmail.hostname=greenmail -Dgreenmail.auth.disabled
  roundcube:
    image: roundcube/roundcubemail:latest
    container_name: roundcube
    hostname: roundcube
    environment:
      - ROUNDCUBEMAIL_SMTP_SERVER=greenmail
      - ROUNDCUBEMAIL_SMTP_PORT=3025
      - ROUNDCUBEMAIL_DEFAULT_HOST=greenmail
      - ROUNDCUBEMAIL_DEFAULT_PORT=3143
    ports:
      - ${ROUNDCUBE_EXPOSED_PORT}:80
    depends_on:
      - greenmail
    restart: always
