name: bonita-sca
services:
  bonita-ui-builder:
    depends_on:
      bonita:
        condition:
          service_healthy
    image: ${UIB_PROJECT_NAME}:${UIB_PROJECT_VERSION}
    # required for MacOs
    platform: linux/arm64
    container_name: bonita-ui
    hostname: bonita-ui-builder
    ports:
      #  exposed port used for health check
      - ${UIB_EXPOSED_PORT}:80
    environment:
      #inside DOCKER compose
      BONITA_API_URL: http://bonita:8080/bonita/API
      BONITA_DEV_MODE: ${UIB_DEV_MODE}
    restart: always

  bonita-ui-proxy:
    image: ${UI_PROXY_IMAGE}:${UI_PROXY_VERSION}
    # required for MacOs
    platform: linux/arm64
    container_name: bonita-ui-proxy
    hostname: bonita-ui-proxy
    ports:
      # don't work
      #      - 8082:8082
      - 80:80
    depends_on:
      bonita-ui-builder:
        condition:
          service_healthy
      bonita:
        condition:
          service_healthy
    environment:
      # don't work
      #      - NGINX_LISTEN_ADDRESS=8082
      #        this uses internal hosts and port
      - BONITA_HOST=bonita
      - BONITA_PORT=8080
      - UIB_HOST=bonita-ui-builder
      - UIB_PORT=80
    restart: always
