name: bonita-sca
services:
  bonita:
    image: ${BONITA_PROJECT_NAME}:${BONITA_PROJECT_VERSION}
    container_name: bonita_sca
    #image: app-hrmanagement-showroom:0.0.1
    hostname: bonita
    volumes:
      - ${LIC_FOLDER}:/opt/bonita_lic/
      - ${BONITA_DATA}/log4j2:/opt/bonita/conf/logs
      - ./bonita/conf/:/opt/custom-config.d/
    ports:
      - ${BONITA_EXPOSED_PORT}:8080
    environment:
      - POSTGRES_ENV_POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - DB_VENDOR=postgres
      - DB_HOST=bonita-db
      - BONITA_RUNTIME_ADMIN_USERNAME=install
      - BONITA_RUNTIME_ADMIN_PASSWORD=install
      - MONITORING_USERNAME=monitoring
      - MONITORING_PASSWORD=mon1tor1ng_adm1n
      - PLATFORM_LOGIN=pfadmin
      - PLATFORM_PASSWORD=pfsecret
      - JMX_REMOTE_ACCESS=false
      - DB_PORT=5432
      - DB_NAME=bonita
      - DB_USER=bonita
      - DB_PASS=bpm
      - BIZ_DB_NAME=business_data
      - BIZ_DB_USER=business_data
      - BIZ_DB_PASS=bpm
      - CLUSTER_MODE=false
      - JAVA_OPTS=-Xms512m -Xmx3000m
      - KEYCLOAK_EXPOSED_PORT=${KEYCLOAK_EXPOSED_PORT}
      - BONITA_EXPOSED_PORT=${BONITA_EXPOSED_PORT}
      - EC2_PUBLIC_HOSTNAME=${EC2_PUBLIC_HOSTNAME}
    restart: always
    depends_on:
#      keycloak:
#        condition:
#          service_healthy
      bonita-db:
        condition:
          service_healthy
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    hostname: keycloak
    container_name: keycloak
    command:
      [
        'start-dev',
        '--import-realm',
      ]
    volumes:
      - ./keycloak/realm-config:/opt/keycloak/data/import:rw
      - ./keycloak/init:/opt/keycloak/bonita_init:rw
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
      - KEYCLOAK_EXPOSED_PORT=${KEYCLOAK_EXPOSED_PORT}
      - BONITA_EXPOSED_PORT=${BONITA_EXPOSED_PORT}
      - BONITA_PROXY_PORT=${BONITA_PROXY_PORT}
      - EC2_PUBLIC_HOSTNAME=${EC2_PUBLIC_HOSTNAME}
    healthcheck:
        test: ["CMD-SHELL", "exec 3<>/dev/tcp/localhost/8080 && echo -e 'GET /health/ready HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3 && cat <&3 | grep -q '200 OK'"]
        interval: 5s
        timeout: 5s
        retries: 30
    ports:
      - ${KEYCLOAK_EXPOSED_PORT}:8080
