name: bonita-sca
services:
  bonita-db:
    container_name: postgresql
    hostname: bonita-db
    #image: bonitasoft/bonita-postgres:latest
    image: bonitasoft/bonita-postgres:${POSTGRESQL_VERSION}
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
